export const createCopy = {
  history: "History",
  loading: "Loading your studio…",
  allTools: (mode: string) => `All ${mode} tools`,
  composerAria: "AI creation controls",
  threadAria: "Generation thread",
  negativePrompt: "Negative prompt",
  negativePlaceholder: "What should the model avoid?",
  privacyNote: "Outputs are private to your Timeless account and project.",
  multiShot: "Multi-shot sequence",
  multiShotHint: "2–5 shots · 3–15 seconds total · One optional first-frame image",
  shotLabel: (n: number) => `Shot ${n}`,
  shotPromptAria: (n: number) => `Shot ${n} prompt`,
  shotSecondsAria: (n: number) => `Shot ${n} seconds`,
  removeShotAria: (n: number) => `Remove shot ${n}`,
  seconds: "Seconds",
  addShot: "Add shot",
  totalSeconds: (n: number) => `${n} seconds total`,
  shotSequenceAria: "Shot sequence",
  promptAria: "Creation prompt",
  promptPlaceholder: (mediaType: string) =>
    mediaType === "audio"
      ? "Paste the script you want spoken…"
      : `Describe the ${mediaType} you want to create…`,
  tool: "Tool",
  model: "Model",
  style: "Style",
  styleAria: "Creative style",
  moreSettings: "More settings",
  generate: "Generate",
  creditsShort: (n: number) => `${n} cr`,
  promptEnhance: "Prompt enhance",
  liveQuote: (model: string, credits: number) => `${model} · ${credits} credits`,
  retentionPolicy: "Files expire after 7 days unless kept",
  shortcut: "⌘ Enter",
  creating: (progress: number) => `${progress || 1}% creating`,
  fileExpired: "File expired",
  expired: "expired",
  refresh: "Refresh",
  export: "Export",
  keep: "Keep",
  creditsCharged: (n: number) => `${n} credits`,
  on: "On",
  off: "Off",
  newThread: "New",
  newThreadAria: "Clear composer for a new generation",
  referenceTile: "Reference",
  referenceTileAria: "Open reference attachments",
  lookTile: "Look",
  lookTileAria: "Open look and style settings",
  lookSummary: (style: string, aspect: string) =>
    aspect ? `${style} · ${aspect}` : style,
  lookDefault: "Style · Auto",
  addReference: "Add",
  useAsReference: "Use this",
  reusePromptAria: "Reuse this prompt",
  cannotUseAsReference: "This tool does not accept references.",
  referenceAttached: "Attached as a reference for the next generate.",
  previousResult: "Previous result",
  succeeded: "Ready",
} as const;
