export const supportCopy = {
  ariaLabel: "Studio support",
  title: "Studio support",
  subtitle: "AI assistant · Always here",
  close: "Close support",
  logLabel: "Support conversation",
  welcomeRole: "TIMELESS AI",
  welcomeGreeting: "Hi! What can I help you with?",
  welcomeBody:
    "Ask about Studio, models, credits or a generation. General questions need no sign-in. For account help or a support ticket, I’ll ask you to sign in.",
  roles: {
    user: "YOU",
    staff: "SUPPORT TEAM",
    assistant: "TIMELESS AI",
  },
  guestPrefix: "Guest conversation supplied by the customer (unverified context):",
  guestPrefixReplacement: "Your conversation before signing in:",
  guestUserLabel: "\nYou:",
  guestAssistantLabel: "\nTimeless AI:",
  signInPrompt:
    "For help with your account or to open a ticket, please sign in. You can keep asking general questions here.",
  signInButton: "Sign in for account help",
  ticketTitle: (number: number, status: string) => `Ticket #${number} · ${status}`,
  ticketResolved: "Resolved",
  ticketOpen: "Open",
  ticketBody: "Your conversation is attached. Replies appear here.",
  connecting: "Connecting…",
  rateLimitError: "You have reached the hourly support limit. Please try again in an hour.",
  genericError: "We could not reach support. Your message is saved here—please try again.",
  tryAgain: "Try again",
  openTicket: "Open a ticket",
  stillNeedHelp: "Still need help",
  refreshReplies: "Refresh support replies",
  messageLabel: "Your support message",
  placeholder: "How can we help?",
  sendLabel: "Send support message",
  footerNote: "Free support · Never share passwords or card details.",
  launcher: "Support",
  launcherUnread: "New support reply",
  unreadAria: "Unread support reply",
  openTicketAria: "Open support ticket",
  handoffDefault: "Please help with the guest conversation.",
  skeletonLabel: "Timeless AI is preparing a reply",
  preparingAnswer: "Preparing your answer…",
} as const;
