export const authCopy = {
  title: "Welcome to Timeless",
  signInLead: "Log in or sign up to bring your ideas to life.",
  signUpLead: "Join Timeless and keep your projects, generations, and credits in one place.",
  continueGoogle: "Continue with Google",
  connectingGoogle: "Connecting to Google…",
  or: "or",
  name: "Name",
  email: "Email",
  password: "Password",
  signIn: "Sign in",
  createAccount: "Create account",
  signingIn: "Signing in…",
  creatingAccount: "Creating account…",
  switchToSignUp: "New to Timeless? Create an account",
  switchToSignIn: "Already have an account? Sign in",
  close: "Close",
  checkEmail: "Check your email to finish creating your Timeless account.",
  defaultDisplayName: "Creator",
} as const;
