import videoModels from "./video-models.json";
import referenceOverrides from "./reference-overrides.json";
export type CatalogModel = { name: string; description: string; modelKey?: string; badge?: string; credits?: number };
type MediaType = "image" | "video" | "audio" | "chat";

export const modelCatalog: Record<MediaType, CatalogModel[]> = {
  image: [
    { name: "Nano Banana 2", description: "Fast image creation and editing", modelKey: "nano-banana-2-1k", badge: "Popular", credits: 12 },
    { name: "FLUX.2 Flex", description: "Detailed cinematic image control", modelKey: "flux-2-flex-1k", credits: 20 },
    { name: "GPT Image 2", description: "Premium text and image rendering", modelKey: "gpt-image-2", badge: "New", credits: 9 },
    { name: "GPT Image 1.5", description: "Creative image generation", modelKey: "gpt-image-1-5", credits: 6 },
    { name: "Seedream 5.0 Lite", description: "Fast photoreal concept generation", modelKey: "seedream-5-lite", badge: "New", credits: 9 },
    { name: "Seedream 5.0 Pro", description: "Art-directed high-detail imagery", modelKey: "seedream-5-pro", badge: "Pro", credits: 11 },
    { name: "Nano Banana Pro", description: "High-fidelity image generation", badge: "Next" },
    { name: "Nano Banana 2 Lite", description: "Fast concept exploration", badge: "New" },
    { name: "Nano Banana", description: "General image generation" },
    { name: "Nano Banana Edit", description: "Prompt-based image editing" },
    { name: "Seedream 4.5", description: "High-quality general image generation" },
    { name: "Seedream 4.5 Edit", description: "Reference-driven image editing" },
    { name: "Imagen 4 Fast", description: "Rapid Google image generation" },
    { name: "Imagen 4", description: "Balanced Google image quality" },
    { name: "Imagen 4 Ultra", description: "Premium photoreal rendering", badge: "Pro" },
    { name: "FLUX.2 Pro", description: "Efficient high-detail image creation" },
    { name: "Grok Imagine Image 2", description: "Photoreal images and edits", badge: "New" },
    { name: "Ideogram V3", description: "Typography and graphic design" },
    { name: "Qwen3 Pro Image", description: "Multilingual image generation" },
    { name: "Recraft", description: "Professional design and enhancement" },
    { name: "Topaz", description: "Image detail and upscale finishing" },
  ].map((listing) => {
    const current = (referenceOverrides as Record<string, {description:string;credit_cost:number;credit_rules:{rates?:Record<string,number>}}>)[listing.modelKey || ""];
    if (!current) return listing;
    const rates = Object.values(current.credit_rules.rates || {}).filter(rate => rate > 0);
    return {...listing, description:current.description, credits:rates.length ? Math.ceil(Math.min(...rates)) : current.credit_cost};
  }),
  video: [
    ...videoModels.map((model) => ({ name: model.name, description: model.description, modelKey: model.key, badge: model.badge, credits: Math.ceil(Math.min(...Object.values(model.credit_rules.rates).filter((rate): rate is number => typeof rate === "number")) * (model.credit_rules.multiplierKey ? Math.min(...(model.parameter_schema.properties.duration?.enum || [1]).map(Number)) : 1)) })),
    { name: "Seedance 1.5 Pro", description: "4–12s video, 480p–1080p, optional audio", modelKey: "seedance-1-5-pro-720p-8s", badge: "Popular", credits: 7 },
    { name: "Kling 3.0", description: "3–15s standard, pro, or 4K video", modelKey: "kling-3-video", badge: "New", credits: 38 },
    { name: "Wan 3.0", description: "Flexible 480p–1080p video", modelKey: "wan-3-video", badge: "New", credits: 36 },
    { name: "Seedance V1 Pro", description: "High-quality general video" },
    { name: "Seedance V1 Lite", description: "Lower-cost motion generation" },
    { name: "Kling 3.0 Omni", description: "Multimodal reference video" },
    { name: "Kling 2.6", description: "Reliable image-to-video" },
    { name: "Kling Motion Control", description: "Transfer movement into a new shot" },
    { name: "Sora 2", description: "Prompt-led scene generation" },
    { name: "Runway", description: "Generative video and extension" },
    { name: "Veo 3.1", description: "High-fidelity cinematic video" },
    { name: "OmniHuman 1.5", description: "Human performance generation" },
  ],
  audio: [
    { name: "ElevenLabs Dialogue v3", description: "Temporarily unavailable while Kie restores audio capacity" },
    { name: "Gemini 3.1 Flash TTS", description: "Temporarily unavailable while the provider route is stabilized" },
    { name: "Gemini 2.5 Pro TTS", description: "Temporarily unavailable while the provider route is stabilized" },
    { name: "ElevenLabs Turbo 2.5", description: "Temporarily unavailable while the provider route is stabilized" },
    { name: "ElevenLabs Multilingual", description: "Temporarily unavailable while the provider route is stabilized" },
    { name: "ElevenLabs Audio Isolation", description: "Voice extraction and cleanup" },
    { name: "Gemini Omni Audio", description: "General audio generation", badge: "New" },
    { name: "Suno (Music)", description: "Original songs and instrumentals" },
    { name: "Suno Cover", description: "Restyle an existing musical idea", badge: "New" },
    { name: "Suno Extend", description: "Continue a generated track", badge: "New" },
    { name: "Suno Add Vocals", description: "Add a vocal layer", badge: "New" },
    { name: "Suno Add Instrumental", description: "Add instrumental backing", badge: "New" },
    { name: "Suno Mashup", description: "Combine musical ideas into one track" },
    { name: "Suno Replace Section", description: "Regenerate one part of a song" },
    { name: "Suno Stem Separation", description: "Split vocals and instruments" },
    { name: "Suno Sound Effects", description: "Generate described sounds" },
    { name: "Suno Lyrics", description: "Generate and time song lyrics" },
    { name: "Suno Audio to MIDI", description: "Convert performance into MIDI" },
  ],
  chat: [
    { name: "GPT 5.2", description: "Creative planning and production", modelKey: "gpt-5-2", badge: "Live", credits: 1 },
    { name: "Claude Opus 4.8", description: "Deep reasoning and long-form work", badge: "Pro" },
    { name: "Claude Sonnet 5", description: "Balanced creative reasoning", badge: "New" },
    { name: "Claude Sonnet 4.5", description: "Writing and structured thinking" },
    { name: "Claude Haiku 4.5", description: "Fast everyday assistance" },
    { name: "Gemini 3 Pro", description: "Multimodal creative reasoning", badge: "New" },
    { name: "Gemini 3 Flash", description: "Fast multimodal chat" },
    { name: "Gemini 2.5 Flash", description: "Efficient ideation" },
    { name: "GPT 5.4", description: "Advanced general reasoning" },
    { name: "GPT 5.5", description: "Creative and technical work", badge: "New" },
    { name: "GPT 5.6 Luna", description: "Fast creator assistance", badge: "New" },
    { name: "GPT 5.6 Terra", description: "Balanced production support" },
    { name: "GPT 5.6 Sol", description: "Reliable agentic production" },
    { name: "Claude Opus 5", description: "Deep premium reasoning", badge: "Pro" },
    { name: "Claude Fable 5", description: "Creative long-form generation" },
    { name: "Claude Opus 4.7", description: "Complex planning and analysis" },
    { name: "Claude Opus 4.6", description: "Long-context production work" },
    { name: "Claude Sonnet 4.6", description: "Balanced everyday reasoning" },
    { name: "Gemini 3.1 Pro", description: "Advanced multimodal reasoning" },
    { name: "Gemini 3.5 Flash", description: "Fast multimodal ideation" },
    { name: "Gemini 3.6 Flash", description: "Efficient production chat" },
    { name: "Gemini 3.7 Flash", description: "Latest fast Google model", badge: "New" },
  ],
};
